function [] = CM_setguidata(appDesDataTable, info, Vrange)   
%{
    Input Parameters: 
    appDesDataTable - data table in app designer
    info        - processed.info, 4 * 17 table
    Vrange      - [parameters.Vrange parameters.Vrange_cathodal [1*88, 1*87]

    Displays performance metrics, and info generated by calcdata.
%}


% numChData = 4
numChData = length(info);

% plots data horizontally, just use text box
for ii=1:numChData
    
    % true for 1 - 4
    if ~isempty(info(ii).VmaxID)

        % false for 1 -4
        if info(ii).noise==0
            info(ii).noise=100;
        end

        tableArray(ii, 1) = string(['n_' num2str(ii) '(t) = ' num2str(round(info(ii).noise*1000)/1000) ' nA']);
        tableArray(ii, 2) = string(['snr_' num2str(ii) ' = ' num2str(info(ii).snr)]);     
        

        % VmaxID (index) greater than or equal to length of Vrange
        if info(ii).VmaxID>=length(Vrange)
            Vmax=0;
        % use VmaxID to index into Vrange vector and return a value
        else
            Vmax=Vrange(info(ii).VmaxID);
        end

        Vmax=Vmax(1);

        tableArray(ii, 3) =  string(['E_o_x_' num2str(ii) ' = ' num2str(round(Vmax*100)/100) ' V']);                      
        tableArray(ii, 4) =  string(['I_o_x_' num2str(ii) ' = ' num2str(round(info(ii).Imax*100)/100) ' nA']);            
        tableArray(ii, 5) =  string(['Iabs' num2str(ii) ' = ' num2str(round(info(ii).Iabs*100)/100) ' nA']);             
        tableArray(ii, 6) =  string(['T_1_/_2' num2str(ii) ' = ' num2str(round(info(ii).thalfSamples*1000)/10) ' ms']);  
        tableArray(ii, 7) =  string(['R' num2str(ii) ' = ' num2str(round(max(info(ii).R)*100)/100)]);                     
        tableArray(ii, 8) =  string(['Q' num2str(ii) ' = ' num2str(round(info(ii).Q)*100/100)]);                          
        tableArray(ii, 9) =  string(['RPH' num2str(ii) ' = ' num2str(round(max(info(ii).RPH)*100)/100)]);                
        tableArray(ii, 10)=  string(['RBG' num2str(ii) ' = ' num2str(round(max(info(ii).RBG)*100)/100)]);              
        tableArray(ii, 11) = string(['RM' num2str(ii) ' = ' num2str(round(max(info(ii).RM)*100)/100)]);                
        
        % false
        if isfield(info,'behav')
            tableArray(ii, 12) = string(['RT target' num2str(ii) ' = ' num2str(round(info(ii).behav.target_rt*1000)) 'ms']);      
            tableArray(ii, 13) = string(['RT fix' num2str(ii) ' = ' num2str(round(info(ii).behav.fix_rt*1000)) 'ms']);            
            tableArray(ii, 14) = string(['Current side' num2str(ii) ' = ' info(ii).behav.currside]);             

            if isfield(info(ii).behav,'currbigside')
                tableArray(ii, 15) = string(['Big side' num2str(ii) ' = ' info(ii).behav.currbigside]);
            else
                tableArray(ii, 15) = "";
            end            
        end        
    end
end

if numChData == 1
    ch1 = tableArray(1, :)';
    appDesDataTable.Data = table(ch1);

elseif numChData == 2
    ch1 = tableArray(1, :)';
    ch2 = tableArray(2, :)';
    appDesDataTable.Data = table(ch1, ch2);
    
elseif numChData == 3
    ch1 = tableArray(1, :)';
    ch2 = tableArray(2, :)';
    ch3 = tableArray(3, :)';
    appDesDataTable.Data = table(ch1, ch2, ch3);

elseif numChData == 4
    ch1 = tableArray(1, :)';
    ch2 = tableArray(2, :)';
    ch3 = tableArray(3, :)';
    ch4 = tableArray(4, :)';
    appDesDataTable.Data = table(ch1, ch2, ch3, ch4);
end    

end