function targrow=getrowxinfos(xinfos,sessnum,siteda,type,event,lfpflag)
%lfpflag==1, then look at sitelfp for siteda supplied
if isempty(lfpflag)
    lfpflag=0;
end
if ~lfpflag
targrow=find(contains({xinfos.sessionid},num2str(sessnum)) &...
    strcmp({xinfos.siteda},siteda) &...
    contains({xinfos.sessiontype},type) &...
    strcmp({xinfos.event},event) );
else
targrow=find(contains({xinfos.sessionid},num2str(sessnum)) &...
    strcmp({xinfos.sitelfp},siteda) &...
    contains({xinfos.sessiontype},type) &...
    strcmp({xinfos.event},event) );
end
end