function [] = setguidata(axPlot, info,Vrange)   
%set text of performance metrics of recorded data, info generated by
%calcdata
subplot(axPlot)
hold(axPlot,'on')
axPos=getpixelposition(axPlot);
plotsize=[200 150];
fontsize=8;
if length(info)>4
    fontsize=7;
end
set(axPlot, 'Units','Pixels','Position',  [axPos(1) axPos(2) plotsize(1) plotsize(2)]);
height=100;
textheight=9;
plot([0:100],[0:100],'color',[1 1 1])
numCH=length(info);
numChData=numCH;
if numCH>4
    numChData=8;
end
aa=0;
xPos=0;
for ii=1:numChData
    if ~isempty(info(ii).VmaxID)
    if info(ii).noise==0
        info(ii).noise=100;
    end
    text(xPos,height-textheight*(aa+0),['n_' num2str(ii) '(t) = ' num2str(round(info(ii).noise*1000)/1000) ' nA'],'color',[1 0 0],'fontsize',fontsize)
    text(xPos,height-textheight*(aa+1),['snr_' num2str(ii) ' = ' num2str(info(ii).snr)],'color',[1 0 0],'fontsize',fontsize)
    if info(ii).VmaxID>=length(Vrange)
        Vmax=0;
    else
        Vmax=Vrange(info(ii).VmaxID);
    end
    Vmax=Vmax(1);
    text(xPos,height-textheight*(aa+2),['E_o_x_' num2str(ii) ' = ' num2str(round(Vmax*100)/100) ' V'],'color',[1 0 0],'fontsize',fontsize)
    text(xPos,height-textheight*(aa+3),['I_o_x_' num2str(ii) ' = ' num2str(round(info(ii).Imax*100)/100) ' nA'],'color',[1 0 0],'fontsize',fontsize)
    text(xPos,height-textheight*(aa+4),['Iabs' num2str(ii) ' = ' num2str(round(info(ii).Iabs*100)/100) ' nA'],'color',[1 0 0],'fontsize',fontsize)
    text(xPos,height-textheight*(aa+5),['T_1_/_2' num2str(ii) ' = ' num2str(round(info(ii).thalfSamples*1000)/10) ' ms'],'color',[1 0 0],'fontsize',fontsize)
    text(xPos,height-textheight*(aa+6),['R' num2str(ii) ' = ' num2str(round(max(info(ii).R)*100)/100)],'color',[1 0 0],'fontsize',fontsize)
    text(xPos,height-textheight*(aa+7),['Q' num2str(ii) ' = ' num2str(round(info(ii).Q)*100/100)],'color',[1 0 0],'fontsize',fontsize)
         text(xPos,height-textheight*(aa+8),['RPH' num2str(ii) ' = ' num2str(round(max(info(ii).RPH)*100)/100)],'color',[1 0 0],'fontsize',fontsize)
         text(xPos,height-textheight*(aa+9),['RBG' num2str(ii) ' = ' num2str(round(max(info(ii).RBG)*100)/100)],'color',[1 0 0],'fontsize',fontsize)
         text(xPos,height-textheight*(aa+10),['RM' num2str(ii) ' = ' num2str(round(max(info(ii).RM)*100)/100)],'color',[1 0 0],'fontsize',fontsize)
    if isfield(info,'behav')
         text(xPos,height-textheight*(aa+11),['RT target' num2str(ii) ' = ' num2str(round(info(ii).behav.target_rt*1000)) 'ms'],'color',[1 0 0],'fontsize',fontsize)
         text(xPos,height-textheight*(aa+12),['RT fix' num2str(ii) ' = ' num2str(round(info(ii).behav.fix_rt*1000)) 'ms'],'color',[1 0 0],'fontsize',fontsize)
         text(xPos,height-textheight*(aa+13),['Current side' num2str(ii) ' = ' info(ii).behav.currside],'color',[1 0 0],'fontsize',fontsize)
        if isfield(info(ii).behav,'currbigside')
         text(xPos,height-textheight*(aa+14),['Big side' num2str(ii) ' = ' info(ii).behav.currbigside],'color',[1 0 0],'fontsize',fontsize)
        end
    end
    if numChData<=4
    xPos=xPos+50;
    else
         xPos=xPos+35;
    end 
    end
    if ii==4        %when plotted on bottom
        aa=aa+12;
        xPos=0;     %reset xPos
    end
end
set(axPlot,'ytick',[])
set(axPlot,'xtick',[])
set (axPlot, 'visible', 'off')
hold(axPlot,'off');
end