function outCIDs=getNumericEvtCodes(outcomeCodes) 
%Just get array of numeric ids for evt codes
%{ 
outcomeCodes={   
    '6'     'break_fix' ...    
    '12'    'break_target'  ...    
    '45'    'reward_big'    ...
    '18'    'reward_big'...
    '19'    'reward_big'...
    '46'    'reward_small'  ...
    '22'    'reward_small'...
    '23'    'reward_small'...
    };
%}
outcomeCodes=reshape(outcomeCodes,2,length(outcomeCodes)/2);
outcomeCodes=outcomeCodes';
outCIDstr=outcomeCodes(:,1);
outCIDs=cellfun(@str2num,outCIDstr);