%chronic 46 channels
ncschannels={
     'p6-p1'...
    'pl2-p4'...
    'cl7-p6'...
     'm2-m4'...
      'eyed'   ...
    'lickx' };

ncschannels={
     'p6-p1'...
    'pl2-p4'...
    'cl7-p6'...
      'eyed'   ...
    'lickx' };