%chronic 46 channels

ncschannels={
    'c5' ...
    'c2' ...
    'c2-c5' ...
    'cl3' ...
    'cl3-c5' ...
    'cl3-c2'...
   'cl3-cl1'...
   'p4'   ...
    'p3'   ...
       'p3-p4'   ...
   'eyed'   ...
    'eyex' };

%get info on whether pc or some other system (ie. chunky) to determine dir
pctype=computer;
ispc=strcmpi(pctype,'pcwin64');
homedir='Z:';
if ~ispc
    homedir=[filesep 'smbshare'];
end
graserver='inj-monkey';
fscvdir='cleo_fscv';

paths{1}=fullfile(homedir,graserver,'raw',fscvdir,'cleo_chronic16_4ch_04102017','1dr','cvtotxt',filesep);
paths{2}=fullfile(homedir,graserver,'raw','cleo','2017-04-10_11-06-25',filesep);