%Patra map pinout CSC channels to electrode names
PCR_srcdir='A:\mit\injectrode\experiments\fscv\templates\pcr_templates\';
PCR_srcdir=fullfile('home','schwerdt','matlab','analysis','analysis','pcr_templates');
PCR_srcdir=[PCR_srcdir filesep];
recordid='noisycleo';
%PCR_template='patra_clean_titanium_da_ph_bg_movep'; %generated cleaner with average of DA in vitro's and non-noisy BG/movement from patra 04/01/2018 for Patra titanium reference causing redox shifts
PCR_template='PCR_invitrophbgda_movement_comb';     %includes in vivo mvmtn from chronic 23, 27, 18 for Cleo analysis

csc_map={
    '2'   'c5'...
    '9'   'cl4' ...
    '11'     'cl3'...
    '12'     'p4' ...
    '14'   'p2'...
    '15'     'p1' ...
    '16'  'p0'...
    '2012'  'c5-p4'...
    '2011'  'c5-cl3'...
    '14016'     'p2-p0' ...
    '12014'     'p4-p2' ...
    '9011'   'cl4-cl3'...
    '902'     'cl4-c5' ...       
    '33'    'eyed'   ...
    '34'    'eyex'  ...
    '35'    'eyey'     
    };

event_codes={
    '4'     'display_fix' ...
    '5'     'start_fix' ...
    '6'     'break_fix' ...
    '10'    'display_target' ...
    '11'    'start_target'  ...
    '12'    'break_target'  ...
    '14'    'error' ...
    '29'    'left_condition'    ...
    '30'    'right_condition'   ...
    '45'    'reward_big'    ...
    '46'    'reward_small'  ...
    };
%07/27/2018 - found out left-condition/right_condition not proper fix spot
%on, need to use "display_fix" instead

%error_trial means fixation break, target fixation break, or something else
%ie # error > fix or target breaks
%but error < fix + target breaks + no enter trials (37)
%# correct trials (ie. id = 13) = = # 45 + #46
%however if we calculate total  trials based on #3 start trial cue) - successful
%trials(#13), get # error trials (14)
%If use #4 (fixspot on) as indicating total trials then this is equal to
%#37 (no enter) + #13 (correct) + #14 (error)
%29 & 30 presented at same as 4

